config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'
  get 'contact', to: 'official#contact', as: 'contact'
  post 'create_contact', to: 'official#create_contact', as: 'create_contact'
  get 'home', to: 'official#home', as: 'home'
  get 'faq', to: 'official#faq', as: 'faq'
  get 'policy', to: 'official#policy', as: 'policy'
  get 'aboutus', to: 'official#aboutus', as: 'aboutus'
  get 'faq2', to: 'official#faq2', as: 'faq2'
  get 'catalog', to: 'official#catalog', as: 'catalog'
  get 'under-maintenance', to: 'publics#under_maintenance', as: 'under_maintenance'
  get '404-not-found', to: 'publics#not_found_page', as: 'not_found_page'
  get "sitemap.xml" => "sitemaps#index", format: "xml", as: 'sitemap'

  resources :blogs
  resources :thank_pages
  resources :pages
  resources :subscribes
  resources :landing_pages
  resources :guest_books
  resources :comments
  resources :products
  resources :helps
  resources :about_us
  resources :contacts
  resources :orders do
    collection do
      get :checkout
    end
    member do
      get :review
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  resources :confirmation_invoices, only: [:new, :create]
  resources :xhrs do
    collection do
      get :cities
      get :shipment_provinces
      get :shipment_cities
      get :shipment_district
      get :shipping_price
      get :sub_categories
      get :sub_categories_catalog
      get :get_invoice_member
      get :get_payment
      get :get_payment_merchant
      get :get_payment_referral
    end
  end

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :recap_payments
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :account_managers do
      collection do
        post :do_multiple_act
      end
    end
    resources :merchants do
      collection do
        post :do_multiple_act
      end
    end
    resources :categories do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        post :do_multiple_act
      end
    end
    resources :orders do
      collection do
        post :do_multiple_act
      end
      member do
        put :change_number_shipping
      end
    end
    resources :order_distributors do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_items do
      collection do
        post :do_multiple_act
      end
    end
    resources :confirmations do
      collection do
        post :do_multiple_act
      end
    end
    resources :affiliates do
      collection do
        post :do_multiple_act
      end
    end
    resources :shipments do
      collection do
        post :do_multiple_act
        post :import
      end
    end
    resources :regions do
      collection do
        post :do_multiple_act
      end
    end
    resources :comments do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :subscribes do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
    resources :catalogs do
      collection do
        post :do_multiple_act
        get :pending
      end
      member do
        get :restore
      end
    end
    resources :packages do
      collection do
        post :do_multiple_act
      end
    end
    resources :invoices do
      collection do
        post :do_multiple_act
      end
    end
    resources :commissions do
      collection do
        post :do_multiple_act
      end
    end
    resources :commission_referrals do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_snapshots do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_merchants do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_referrals do
      collection do
        post :do_multiple_act
      end
    end
    resources :domain_settings do
      collection do
        post :do_multiple_act
      end
    end
    resources :guest_books
    resources :web_templates do
      collection do
        post :do_multiple_act
      end
    end
    resources :report_refunds do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_presses do
      collection do
        post :do_multiple_act
      end
    end
    resources :request_landing_presses
    resources :brands
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :spendings do
      collection do
        post :do_multiple_act
      end
    end

  end

  namespace :members do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members, only: [:edit, :update, :show]
    get 'change_theme', to: 'members#change_theme', as: 'change_theme'
    put 'update_change_theme/:id', to: 'members#update_change_theme', as: 'update_change_theme'
    resources :catalogs do
      collection do
        get :inactive
        get :pending
        get :archive
        get :download_catalogs
      end
      member do
        get :restore
        put :change_status
      end
    end
    resources :orders do
      member do
        get :detail
      end
    end
    resources :confirmations
    resources :commissions do
      collection do
        get :referral
      end
    end
    resources :payments
    resources :packages do
      collection do
        get :upgrade
      end
    end
    resources :referrals
    resources :settings
    resources :invoices
    resources :affiliates
    resources :managers
    resources :messages
    resources :guest_books
    resources :blogs
    resources :request_landing_presses
    resources :shops do
      member do
        get :review
      end
      collection do
        get :cart
        get :checkout
      end
    end
    resources :report_refunds
    resources :payment_referrals
  end

  namespace :managers do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :account_managers, only: [:edit, :update, :show]
    resources :catalogs do
      collection do
        get :inactive
        get :pending
        get :archive
        get :download_catalogs
      end
      member do
        get :restore
        put :change_status
      end
    end
    resources :orders do
      member do
        get :detail
      end
    end
    resources :confirmations
    resources :commissions
    resources :payments
    resources :invoices
    resources :members do
      member do
        get :click_message
      end
    end
    resources :messages do
      collection do
        post :blast_message
      end
    end
    resources :report_refunds
  end

  namespace :merchants do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :products
    resources :merchants
    resources :payments
    resources :orders do
      member do
        put :change_number_shipping
      end
    end
    resources :order_items
  end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::ApplicationController
  defaults resource_class: Member, collection_name: 'members', instance_name: 'member'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Members", :collection_path

  include MultipleAction

  def index
    @verifieds = collection.verified.active.size 
    @featureds = collection.verified.active.featured.size
    @not_verifieds = collection.not_verified.size
    @not_actives = collection.not_active.size

    if params[:export] == 'true'
      @collection_all = collection
    end
    
    @collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html
      format.js
      format.xls
    end
  end

  def show
    @domain_settings = resource.domain_settings.page(params[:page_domain_settings]).per(per_page)
    @catalogs = resource.catalogs.latest.search_by(params).page(params[:page_catalogs]).per(per_page)
    @orders = resource.orders.latest.search_by(params).page(params[:page_orders]).per(per_page)
    @confirmations = resource.confirmations.latest.search_by(params).page(params[:page_confirmations]).per(per_page)
    @commissions = resource.commissions.latest.search_by(params).page(params[:page_commissions]).per(per_page)
    @commission_referrals = resource.commission_referrals.latest.search_by(params).page(params[:page_commission_referrals]).per(per_page)
    @payment_snapshots = resource.payment_snapshots.latest.search_by(params).page(params[:page_payment_snapshots]).per(per_page)
    @payment_referrals = resource.payment_referrals.latest.search_by(params).page(params[:page_payment_referrals]).per(per_page)
    @report_refunds = resource.report_refunds.latest.search_by(params).page(params[:page_report_refunds]).per(per_page)
    @invoices = resource.invoices.latest.search_by(params).page(params[:page_invoices]).per(per_page)
    @referrals = resource.referrals.latest.search_by(params).page(params[:page_referrals]).per(per_page)
    @request_landing_presses = resource.request_landing_presses.latest.search_by(params).page(params[:page_request_landing_presses]).per(per_page)
    @activities = resource.activities.latest.search_by(params).page(params[:page_activities]).per(per_page)
    @referral_verified = @referrals.verified
    @referral_not_verified = @referrals.not_verified
    @referral_referral1 = @referrals.referral1(resource.id)
    @referral_referral2 = @referrals.referral2(resource.id)
    @referral_referral3 = @referrals.referral3(resource.id)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    super
    new_account_manager = params[:member][:account_manager_id].to_i
    if resource.catalogs.present?
      resource.catalogs.each do |c|
        if new_account_manager != c.account_manager_id
          c.account_manager_id = new_account_manager
          c.save
        end
      end
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by_member(params)
    end
end

app/controllers/backend/payment_referrals_controller.rb
class Backend::PaymentReferralsController < Backend::ApplicationController
  defaults resource_class: PaymentReferral, collection_name: 'payment_referrals', instance_name: 'payment_referral'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Payment Referrals", :collection_path

  include MultipleAction

  def index
    @collection_pending = collection.pending.sum(:commission_referral)
    @collection_process = collection.process.sum(:commission_referral)
    @collection_paid = collection.paid.sum(:commission_referral)
    @collection_rejects = collection.rejects.sum(:commission_referral)

    if params[:export] == 'true'
      @collection_all = collection.latest
    end
    
    @collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html
      format.js
      format.xls
    end
  end

  def show
    @activities = resource.activities.latest.search_by(params).page(params[:page_activities]).per(per_page)
    
    respond_to do |format|
      format.html
      format.js
      format.pdf do
        render pdf: "Pembayaran referral - #{helpers.get_date(resource.payment_start)} s.d. #{helpers.get_date(resource.payment_end)}",
        layout: 'layouts/print_layout.html.erb',
        show_as_html: params[:debug].present?
      end
    end
  end

  def create
    member_id = params[:payment_referral][:member_id]

    member = Member.find member_id
    payment_start = params[:payment_referral][:payment_start]
    payment_end = params[:payment_referral][:payment_end]
    status = params[:payment_referral][:status]
    from_acc = params[:from_acc]
    to_acc = params[:to_acc]
    message = params[:message]
    
    @payment_referral = build_resource
    @payment_referral.admin_id = current_user.id

    commission_referrals = CommissionReferral.where("commission_referrals.member_id =? AND DATE(commission_referrals.commission_date) >=? AND DATE(commission_referrals.commission_date) <=? AND commission_referrals.status =?", member_id, payment_start, payment_end, CommissionReferral::APPROVED)
    @to_acc = member.profile.payment_to

    @payment_referral.commission_referral = '%.4f' % commission_referrals.sum(:commission_value)
    @payment_referral.from_acc = from_acc
    @payment_referral.to_acc = to_acc
    @payment_referral.message = message
    @payment_referral.status = status
    
    orders = member.orders.where("DATE(orders.purchased_at) >=? AND DATE(orders.purchased_at) <=? AND orders.order_status_id =?", payment_start, payment_end, 3)
    total_order = '%.4f' % orders.sum(:total_price)
    if total_order.to_f >= PaymentReferral::ORDER_TARGET
      @payment_referral.payment_pending = false
    else
      @payment_referral.quote = PaymentReferral::QUOTE
    end

    if @payment_referral.save
      # @payment_referral.total_delay = member.payment_referrals.delay.count
      @payment_referral.save
      create_activity(@payment_referral, current_user.id, "Pembayaran Referral (#{@payment_referral.member.username})", "#{current_user.username} membuat pembayaran periode #{@payment_referral.payment_period?} sebesar #{@payment_referral.get_commission_referral?}.")
      redirect_to backend_payment_referrals_path, notice: "Successfully created payment referrals"
    else
      redirect_to backend_payment_referrals_path, alert: "Unsuccessfully created payment referrals, #{@payment_referral.errors.full_messages.join(',')}"
    end
  end

  def update
    resource
    member_id = @payment_referral.member_id

    member = Member.find member_id
    payment_start = params[:payment_referral][:payment_start]
    payment_end = params[:payment_referral][:payment_end]
    status = params[:payment_referral][:status]
    from_acc = params[:from_acc].present? ? params[:from_acc] : params[:payment_referral][:from_acc]
    to_acc = params[:to_acc].present? ? params[:to_acc] : params[:payment_referral][:to_acc]
    message = params[:message].present? ? params[:message] : params[:payment_referral][:message]

    if Time.zone.now.to_date > payment_end.to_date
      if check_data_update(member_id, payment_start, payment_end).present?
        @payment_referral.admin_id = current_user.id

        commission_referrals = CommissionReferral.where("commission_referrals.member_id =? AND DATE(commission_referrals.commission_date) >=? AND DATE(commission_referrals.commission_date) <=? AND commission_referrals.status =?", member_id, payment_start, payment_end, CommissionReferral::APPROVED)
        @to_acc = member.profile.payment_to

        @payment_referral.commission_referral = '%.4f' % commission_referrals.sum(:commission_value)
        @payment_referral.from_acc = from_acc
        @payment_referral.to_acc = to_acc
        @payment_referral.message = message
        @payment_referral.status = status
        if @payment_referral.save
          redirect_to backend_payment_referrals_path, notice: "Successfully created payment referrals"
        else
          redirect_to backend_payment_referrals_path, alert: "Unsuccessfully created payment referrals, #{@payment_referral.errors.full_messages.join(',')}"
        end
        
      else
        redirect_back(fallback_location: backend_payment_referrals_path, alert: "Unsuccessfully updated #{@resource_name} because #{member.username} period #{payment_start} - #{payment_end} has never entered!")
      end
    else
      redirect_back(fallback_location: backend_payment_referrals_path, alert: "Unsuccessfully updated #{@resource_name} because payment_end selected is bigger than this day!")
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end

    def check_data_update(member_id, payment_start, payment_end)
      payment_referral = PaymentReferral.where("payment_referrals.member_id =? AND payment_referrals.payment_start =? AND payment_referrals.payment_end =?", member_id, payment_start, payment_end).where.not(status: PaymentReferral::PAID)
      return payment_referral
    end
end

app/controllers/members/affiliates_controller.rb
class Members::AffiliatesController < Members::ApplicationController
	defaults resource_class: Affiliate, collection_name: 'affiliates', instance_name: 'affiliate'

  add_breadcrumb "Dashboard", :members_dashboard_path
  add_breadcrumb "Affiliates", :collection_path

  def index
    @collection_pending = collection.pending.sum(:fee_member)
    @collection_process = collection.process.sum(:fee_member)
    @collection_paid = collection.paid.sum(:fee_member)
    @collection_rejects = collection.rejects.sum(:fee_member)

    @collection_size = collection.size

    if params[:export] == 'true'
      @collection_all = collection.latest
    end
  	@collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html 
      format.xls
      format.js
      format.xls
    end
  end

  protected
    def collection
       @collection = @member.affiliates.search_by(params)
    end
end

app/views/members/payment_referrals/_content_info.html.slim
.col-md-6
  = render 'members/shareds/target_omset', total_order: @last_total_orders, total_order_percent: @last_order_percent, start_at: @beginning_of_last, end_at: @end_of_last, omset: "Last Pembelian", class_progress: "last_omset"

.col-md-6
  = render 'members/shareds/target_omset', total_order: @ongoing_total_orders, total_order_percent: @ongoing_order_percent, start_at: @beginning_of_ongoing, end_at: @end_of_ongoing, omset: "Ongoing Pembelian", class_progress: "ongoing_omset"
  
.col-md-12
	a aria-controls="collapseOne" aria-expanded="true" data-parent="#accordion" data-toggle="collapse" href="#collapseOne" role="button" class="btn-how-to-use btn-default btn btn-full"
		| Tampilkan Langkah Pembayaran
.how-to-use id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne"
	.col-payment
		.box-payment
			i.pe-7s-date.fa-4x
			br
			small
				| Periode pembayaran Dropshipan dibagi 2 setiap bulan, contoh: 
				| 1-15. dan 16-akhir bulan.
			.nomber-step
				| 1
	.col-payment	
		.box-payment
			i.pe-7s-id.fa-4.fa-4x
			br
			small
				| "Memproses" menyetujui keuangan pembayaran anda
			.nomber-step
				| 2
	.col-payment	
		.box-payment
			i.pe-7s-cash.fa-4x
			br
			small
				| Kami mengirimkan pembayaran anda langsung ke rekening terdaftar
			.nomber-step
				| 3
	.col-payment	
		.box-payment
			i.pe-7s-clock.fa-4x
			br
			small
				| Pembayaran bisa memakan waktu antara 4 hingga 5 hari untuk diselesaikan
			.nomber-step
				| 4
	.col-payment	
		.box-payment
			i.pe-7s-ribbon.fa-4x
			br
			small
				| "Berbayar" Status pembayaran anda diperbarui dan ditandai
			.nomber-step
				| 5

app/views/members/payment_referrals/_partial_js.html.slim
= render 'content_info'
= render 'search_payment'
= render 'table_payment'

app/views/members/payment_referrals/_search_payment.html.slim
.col-md-4
	= form_for :search, url: collection_path, html: {class: 'js-form-analytic'}, method: 'get', remote: true do 
		.box-keyword
			.form-group
				label Keyword
				= text_field_tag :key, params[:key], placeholder: 'Invoice/code', class: "form-control"
			.form-group
				label Status
				= select_tag :status, options_for_select(PaymentReferral::STATUSES, params[:status]), prompt: 'Pilih Status', class: 'form-control'
			.form-group
				label Status Payment
				= select_tag :status_payment, options_for_select(PaymentReferral::STATUSES_PAYMENT, params[:status_payment]), prompt: 'Pilih Status Payment', class: 'form-control'
			.form-group
				label Start Date
				.input-group.date
					span.input-group-addon
						span.fa.fa-calendar
					= text_field_tag :start_at, nil, value: params[:start_at], class: 'datepicker form-control', placeholder: 'Start At'
			.form-group
				label End Date
				.input-group.date
					span.input-group-addon
						span.fa.fa-calendar
					= text_field_tag :end_at, nil, value: params[:end_at], class: 'datepicker form-control', placeholder: 'End At'
			.form-group
				= submit_tag 'Search', class: "btn btn-full btn-gb"
			.form-group
				.js-button-export
					= render 'shareds/button_export'

app/views/members/payment_referrals/_table_payment.html.slim
.col-md-8
	- if @collection.blank?
		= render "shareds/empty_blank"
	- else
		- @collection.each_with_index do |resource, index|
			ul.timeline
				li.timeline-inverted
					.timeline-badge
						i.pe-7s-note2
					.timeline-panel
						.timeline-heading
							.row
								.col-md-8
									h4
										b
											i.fa.fa-globe &nbsp;
											= resource.code 
								.col-md-4
									h6.uppercase.tright
										= get_datetime(resource.created_at)
						.timeline-body
							.row
								.content-timeline
									.col-md-6.col-sm-6
										h5
											| Transfer Dari
										h5 
											b
												= resource.from_acc
									.col-md-6.col-sm-6
										h5
											| Ke
										h5 
											b 
												= resource.to_acc
								.col-xs-12
									.table-responsive
										table.table
											thead
												tr
													th Periode
													th Komisi
													th Status
													th Status Payment
											tbody
												tr
													td
														- if resource.payment_start.present? 
															= resource.payment_period?
															
														- else
															| -
													td
														= get_currency(resource.commission_referral)
													td
														= resource.status?
													td
														= resource.status_payment?
									- if resource.message.present?
										h5
											b Pesan :
											| &nbsp;
											| #{resource.message}
									- if resource.quote.present?
										h5
											b Keterangan :
											| &nbsp;
											| #{resource.quote}
				.btn-right
					= link_to '<i class="fa fa-download" aria-hidden="true"></i> Generate PDF'.html_safe, members_payment_referral_path(resource.code, format: 'pdf'), class: 'btn btn-gb btn-g'
			br
	.widget-foot
		= paginate @collection, remote: true

app/views/members/payment_referrals/index.html.slim
#wrapper.use
  .content.animate-panel
    .hpanel
      .title-member-content.mg-bot15
        b Pembayaran Referral
      .row
        .js-partial_js
          = render 'partial_js'

app/views/members/payment_referrals/index.js.erb
<%= render partial: 'shareds/js/analytic', formats: [:js] %>

app/views/members/payment_referrals/index.xls.erb
<table border="1">
  <caption>Daftar Pembayaran Referral <%= show_search_form_date(params[:start_at], params[:end_at]) %></caption>
  <tr>
    <th>Kode Invoice</th>
    <th>Username</th>
    <th>Komisi</th>
    <th>Dari</th>
    <th>Pesan</th>
    <th>Status</th>
    <th>Status Payment</th>
    <th>Periode</th>
    <th>Dibuat</th>
  </tr>
  <% @collection_all.each_with_index do |resource, index| %>
  <tr>
    <td><%= resource.code %></td>
    <td><%= "(#{resource.member_id}) #{resource.member.username}" %></td>
    <td><%= get_currency(resource.commission_referral) %></td>
    <td><%= "#{resource.from_acc} Ke #{resource.to_acc}" %></td>
    <td><%= "#{resource.message}" %></td>
    <td><%= resource.status? %></td>
    <td><%= resource.status_payment? %></td>
    <td><%= resource.payment_period? %></td>
    <td><%= get_datetime(resource.created_at) %></td>
  </tr>
  <% end %>
</table>

app/views/members/payment_referrals/show.pdf.slim
section.invoice
	.row
		.col-md-12
			h4.page-header
				i.fa.fa-globe &nbsp;
				= @resource.code
				small.date-invoice.pull-right #{get_datetime(@resource.created_at)}
	.row.invoice-info
		.col-md-6.col-sm-6.invoice-col
			| Transfer Dari
			address
				b= @resource.from_acc
		.col-md-6.col-sm-6.invoice-col
			| Ke
			address
				b= @resource.to_acc
	.row
		.col-xs-12
			.table-responsive
				table.table.table-striped.table-bordered
					thead
						tr
							th Periode
							th Komisi Referral
							th Status
							th Status Payment
					tbody
						tr
							td
								- if @resource.payment_start.present? 
									= @resource.payment_period?
									
								- else
									| -
							td
								= get_currency(@resource.commission_referral)
							td
								= @resource.status?
							td
								= @resource.status_payment?
			- if @resource.message.present?
				h6
					b Pesan :
					| &nbsp;
					| #{@resource.message}
			- if @resource.quote.present?
				h6
					b Keterangan :
					| &nbsp;
					| #{@resource.quote}