config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'
  get 'contact', to: 'official#contact', as: 'contact'
  post 'create_contact', to: 'official#create_contact', as: 'create_contact'
  get 'home', to: 'official#home', as: 'home'
  get 'faq', to: 'official#faq', as: 'faq'
  get 'policy', to: 'official#policy', as: 'policy'
  get 'aboutus', to: 'official#aboutus', as: 'aboutus'
  get 'faq2', to: 'official#faq2', as: 'faq2'
  get 'catalog', to: 'official#catalog', as: 'catalog'
  get 'under-maintenance', to: 'publics#under_maintenance', as: 'under_maintenance'
  get '404-not-found', to: 'publics#not_found_page', as: 'not_found_page'
  get "sitemap.xml" => "sitemaps#index", format: "xml", as: 'sitemap'

  resources :blogs
  resources :thank_pages
  resources :pages
  resources :subscribes
  resources :landing_pages
  resources :guest_books
  resources :comments
  resources :products
  resources :helps
  resources :about_us
  resources :contacts
  resources :orders do
    collection do
      get :checkout
    end
    member do
      get :review
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  resources :confirmation_invoices, only: [:new, :create]
  resources :xhrs do
    collection do
      get :cities
      get :shipment_provinces
      get :shipment_cities
      get :shipment_district
      get :shipping_price
      get :sub_categories
      get :sub_categories_catalog
      get :get_invoice_member
      get :get_payment
      get :get_payment_merchant
      get :get_payment_referral
    end
  end

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :recap_payments
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :account_managers do
      collection do
        post :do_multiple_act
      end
    end
    resources :merchants do
      collection do
        post :do_multiple_act
      end
    end
    resources :categories do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        post :do_multiple_act
      end
    end
    resources :orders do
      collection do
        post :do_multiple_act
      end
      member do
        put :change_number_shipping
      end
    end
    resources :order_distributors do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_items do
      collection do
        post :do_multiple_act
      end
    end
    resources :confirmations do
      collection do
        post :do_multiple_act
      end
    end
    resources :affiliates do
      collection do
        post :do_multiple_act
      end
    end
    resources :shipments do
      collection do
        post :do_multiple_act
        post :import
      end
    end
    resources :regions do
      collection do
        post :do_multiple_act
      end
    end
    resources :comments do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :subscribes do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
    resources :catalogs do
      collection do
        post :do_multiple_act
        get :pending
      end
      member do
        get :restore
      end
    end
    resources :packages do
      collection do
        post :do_multiple_act
      end
    end
    resources :invoices do
      collection do
        post :do_multiple_act
      end
    end
    resources :commissions do
      collection do
        post :do_multiple_act
      end
    end
    resources :commission_referrals do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_snapshots do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_merchants do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_referrals do
      collection do
        post :do_multiple_act
      end
    end
    resources :domain_settings do
      collection do
        post :do_multiple_act
      end
    end
    resources :guest_books
    resources :web_templates do
      collection do
        post :do_multiple_act
      end
    end
    resources :report_refunds do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_presses do
      collection do
        post :do_multiple_act
      end
    end
    resources :request_landing_presses
    resources :brands
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :spendings do
      collection do
        post :do_multiple_act
      end
    end

  end

  namespace :members do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members, only: [:edit, :update, :show]
    get 'change_theme', to: 'members#change_theme', as: 'change_theme'
    put 'update_change_theme/:id', to: 'members#update_change_theme', as: 'update_change_theme'
    resources :catalogs do
      collection do
        get :inactive
        get :pending
        get :archive
        get :download_catalogs
      end
      member do
        get :restore
        put :change_status
      end
    end
    resources :orders do
      member do
        get :detail
      end
    end
    resources :confirmations
    resources :commissions do
      collection do
        get :referral
      end
    end
    resources :payments
    resources :packages do
      collection do
        get :upgrade
      end
    end
    resources :referrals
    resources :settings
    resources :invoices
    resources :affiliates
    resources :managers
    resources :messages
    resources :guest_books
    resources :blogs
    resources :request_landing_presses
    resources :shops do
      member do
        get :review
      end
      collection do
        get :cart
        get :checkout
      end
    end
    resources :report_refunds
    resources :payment_referrals
  end

  namespace :managers do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :account_managers, only: [:edit, :update, :show]
    resources :catalogs do
      collection do
        get :inactive
        get :pending
        get :archive
        get :download_catalogs
      end
      member do
        get :restore
        put :change_status
      end
    end
    resources :orders do
      member do
        get :detail
      end
    end
    resources :confirmations
    resources :commissions
    resources :payments
    resources :invoices
    resources :members do
      member do
        get :click_message
      end
    end
    resources :messages do
      collection do
        post :blast_message
      end
    end
    resources :report_refunds
  end

  namespace :merchants do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :products
    resources :merchants
    resources :payments
    resources :orders do
      member do
        put :change_number_shipping
      end
    end
    resources :order_items
  end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::ApplicationController
  defaults resource_class: Member, collection_name: 'members', instance_name: 'member'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Members", :collection_path

  include MultipleAction

  def index
    @verifieds = collection.verified.active.size 
    @featureds = collection.verified.active.featured.size
    @not_verifieds = collection.not_verified.size
    @not_actives = collection.not_active.size

    if params[:export] == 'true'
      @collection_all = collection
    end
    
    @collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html
      format.js
      format.xls
    end
  end

  def show
    @domain_settings = resource.domain_settings.page(params[:page_domain_settings]).per(per_page)
    @catalogs = resource.catalogs.latest.search_by(params).page(params[:page_catalogs]).per(per_page)
    @orders = resource.orders.latest.search_by(params).page(params[:page_orders]).per(per_page)
    @confirmations = resource.confirmations.latest.search_by(params).page(params[:page_confirmations]).per(per_page)
    @commissions = resource.commissions.latest.search_by(params).page(params[:page_commissions]).per(per_page)
    @commission_referrals = resource.commission_referrals.latest.search_by(params).page(params[:page_commission_referrals]).per(per_page)
    @payment_snapshots = resource.payment_snapshots.latest.search_by(params).page(params[:page_payment_snapshots]).per(per_page)
    @payment_referrals = resource.payment_referrals.latest.search_by(params).page(params[:page_payment_referrals]).per(per_page)
    @report_refunds = resource.report_refunds.latest.search_by(params).page(params[:page_report_refunds]).per(per_page)
    @invoices = resource.invoices.latest.search_by(params).page(params[:page_invoices]).per(per_page)
    @referrals = resource.referrals.latest.search_by(params).page(params[:page_referrals]).per(per_page)
    @request_landing_presses = resource.request_landing_presses.latest.search_by(params).page(params[:page_request_landing_presses]).per(per_page)
    @activities = resource.activities.latest.search_by(params).page(params[:page_activities]).per(per_page)
    @referral_verified = @referrals.verified
    @referral_not_verified = @referrals.not_verified
    @referral_referral1 = @referrals.referral1(resource.id)
    @referral_referral2 = @referrals.referral2(resource.id)
    @referral_referral3 = @referrals.referral3(resource.id)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    super
    new_account_manager = params[:member][:account_manager_id].to_i
    if resource.catalogs.present?
      resource.catalogs.each do |c|
        if new_account_manager != c.account_manager_id
          c.account_manager_id = new_account_manager
          c.save
        end
      end
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by_member(params)
    end
end

app/controllers/backend/orders_controller.rb
class Backend::OrdersController < Backend::ApplicationController
  defaults resource_class: Order, collection_name: 'orders', instance_name: 'order'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Orders", :collection_path

  include MultipleAction

  def index
    collection_default = collection
    if current_user.checker_2?
      collection_default = collection_default.track_verification_packing_cancelled
    elsif current_user.shipment?
      collection_default = collection_default.paid.track_packing_shipped
    elsif current_user.checker_3?
      collection_default = collection_default.paid.track_shipped_received
    end

    @order_in_progress = collection_default.in_progress
    @order_verification = collection_default.verification
    @order_paid = collection_default.paid
    @order_cancelled = collection_default.cancelled
    @reports_collect = collection_default.latest

    if params[:export] == 'true'
      @collection_all = @reports_collect
    end
    
    @collection = collection_default.without_in_progress.latest.page(page).per(per_page)

    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def show
    @confirmation = Confirmation.where("LOWER(confirmations.no_invoice) LIKE LOWER('#{resource.code}')").first
    @stakeholders = resource.stakeholder_orders.latest
    @activities = resource.activities.latest.search_by(params).page(params[:page_activities]).per(per_page)

    respond_to do |format|
      format.html
      format.js
      format.pdf do
        render pdf: "Invoice Order - #{resource.code}",
        layout: 'layouts/print_layout.html.erb',
        show_as_html: params[:debug].present?
      end
    end
  end

  def update
    @old_status = resource.order_status_id
    @old_status_shipping = resource.track_order
    update! do |format|
      if resource.errors.empty?
        resource.prepare_status_payment
        update_order(resource)
        format.html {redirect_to request.referer || root_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to request.referer || root_path}
      end
    end
  end

  def change_number_shipping
    order = Order.find(params[:id])
    number_shipping_old = order.number_shipping
    number_shipping_new = params[:order][:number_shipping]
    order.number_shipping = number_shipping_new
    if order.save
      UserMailer.order_shipped(order).deliver if number_shipping_old.blank? && number_shipping_new.present?
      create_activity(order, current_user.id, "Resi Pesanan", "#{current_user.username} memasukkan resi pesanan '#{order.number_shipping}'.")
      redirect_back(fallback_location: root_path, notice: "Nomor resi pengiriman berhasil disimpan!")
    else
      redirect_back(fallback_location: root_path, notice: "Nomor resi pengiriman gagal disimpan!")
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end

    def update_order(order)
      if order.save
        Order.update_order(order, @old_status, @old_status_shipping)
        create_activity(order, current_user.id, "Status Pesanan (#{order.status_text?})", "#{current_user.username} mengubah status pesanan dari '#{Order.check_status_text(@old_status)}' menjadi '#{order.status_text?}'.") unless @old_status == order.order_status_id
        if @old_status_shipping == Order::VERIFICATION
          old_status_shipping = Order.check_status_text(@old_status)
        else
          old_status_shipping = Order.check_status_order_text(@old_status_shipping)
        end
        create_activity(order, current_user.id, "Status Pesanan (#{order.status_order_text?})", "#{current_user.username} mengubah status pesanan dari '#{old_status_shipping}' menjadi '#{order.status_order_text?}'.") unless @old_status_shipping == order.track_order
      end
      return order
    end
end

app/controllers/managers/members_controller.rb
class Managers::MembersController < Managers::ApplicationController
  defaults resource_class: Member, collection_name: 'members', instance_name: 'member'

  add_breadcrumb "Dashboard", :managers_dashboard_path
  add_breadcrumb "Resellers", :collection_path

  def index
    @collection_size = collection.size

    if params[:export] == 'true'
      @collection_all = collection.latest
    end
    @collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def show
    add_breadcrumb "messages"
    if resource.account_manager_id == current_user.id
      @profile = resource.profile
      check_group_message_member(@manager.id, resource.id)

      if @latest_messages.where(from: resource.id).present?
        @latest_messages.where(from: resource.id).each do |m|
          m.status = 'read'
          m.save
        end
      end
    else
      redirect_to :back, alert: "You can not access this page because he/she is not your reseller."
    end
  end

  def click_message
    message = Message.find(params[:message_id])
    message.status = "read"
    message.save

    redirect_to managers_member_path(params[:id])
  end
  
  protected
    def collection
       @collection = @manager.members.search_by_member(params)
    end
end

app/controllers/managers/orders_controller.rb
class Managers::OrdersController < Managers::ApplicationController
  defaults resource_class: Order, collection_name: 'orders', instance_name: 'order'
  
  add_breadcrumb "Dashboard", :managers_dashboard_path
  add_breadcrumb "Pesanan", :collection_path

  def index
    order_report_day(@manager.orders.without_in_progress, 'with_search_by', :price, params[:export])
  end

  def show
    add_breadcrumb "#{params[:id]}"
    super
  end

  def detail
    add_breadcrumb "Konfirmasi Pembayaran", managers_confirmations_path
    add_breadcrumb "Detail"
    @confirmation = Confirmation.where("LOWER(confirmations.no_invoice) LIKE LOWER('#{params[:id]}')").first
    @order = Order.find_by(code: @confirmation.no_invoice.downcase)
  end

end

app/controllers/members/affiliates_controller.rb
class Members::AffiliatesController < Members::ApplicationController
	defaults resource_class: Affiliate, collection_name: 'affiliates', instance_name: 'affiliate'

  add_breadcrumb "Dashboard", :members_dashboard_path
  add_breadcrumb "Affiliates", :collection_path

  def index
    @collection_pending = collection.pending.sum(:fee_member)
    @collection_process = collection.process.sum(:fee_member)
    @collection_paid = collection.paid.sum(:fee_member)
    @collection_rejects = collection.rejects.sum(:fee_member)

    @collection_size = collection.size

    if params[:export] == 'true'
      @collection_all = collection.latest
    end
  	@collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html 
      format.xls
      format.js
      format.xls
    end
  end

  protected
    def collection
       @collection = @member.affiliates.search_by(params)
    end
end

app/views/members/orders/_estimate.html.slim
- if current_user.merchant?
  - column = "cold-md-6 col-sm-6"
- else
  - column = "cold-md-4 col-sm-4"
  

.row
  .col-md-4.col-sm-4
    .box-dashboard-info
      .title-info.text-center
        | Total Penjualan
      .box-content-info
        i.pe-7s-cash.width
        .txt
          - if current_user.merchant?
            = get_currency(@reports_collect.paid.pluck(:basic_price).sum)
          - else
            = get_currency(@reports_collect.paid.pluck(:price).sum)

        .detail
          | Transaksi
          .bg
            = @reports_collect.paid.size

  .col-md-4.col-sm-4
    .box-dashboard-info
      .title-info.text-center
        | Total Pengiriman
      .box-content-info
        i.pe-7s-plane
        .txt
          = get_currency(@reports_collect.paid.pluck(:shipping_price).sum)
        .detail
          | Pengiriman
          .bg
            = @reports_collect.paid.size
  - if current_user.merchant?
    .col-md-4.col-sm-4
      .box-dashboard-info
        .title-info.text-center
          | Total Omset
        .box-content-info
          i.pe-7s-wallet
          .txt
            = get_currency(@reports_collect.paid.pluck(:total_basic_price).sum)
  -else
    .col-md-4.col-sm-4
      .box-dashboard-info
        .title-info.text-center
          | Total Komisi
        .box-content-info
          i.pe-7s-wallet
          .txt
            = get_currency(@commission_default.pluck(key).sum)

  div class="#{column}"
    .box-trafic
      = image_tag '4.png'
      .desc-trafic
        b
          = @order_paid.size
        br
        | Total Order Dibayar

  -unless current_user.merchant?
    .col-md-4.col-sm-4
      .box-trafic
        = image_tag '3.png'
        .desc-trafic
          b
            = @order_verification.size
          br
          | Total Order Diperiksa
          
  div class="#{column}"
    .box-trafic
      = image_tag '1.png'
      .desc-trafic
        b
          = @order_cancelled.size
        br
        | Total Order Dibatalkan

app/views/members/orders/_invoice.html.slim
.hpanel
  .col-md-4
    .row
      .title-member-content 
        b Detail Order
  .col-md-8
    .row
      = render 'members/orders/order_menu'
  .col-md-12
    = render 'members/orders/progress'

  .col-md-12
    - if @confirmation.present?
      .row
        .panel-body.mg-top15
          .title-show-confirmation
            | KONFIRMASI 
            b #{@confirmation.no_invoice}
            .desc.mg-top10
              b Tanggal Pembayaran : 
              = @confirmation.try(:payment_date).strftime("%B, %d, %Y") if @confirmation.payment_date
            .desc.mg-bot10
              b Nama Pembeli : 
              = @confirmation.try(:name)
              | (#{@confirmation.try(:email)})
          .table-responsive
            table.table.table-striped.table-bordered.table-hover.mg-top10
              thead.thead-detail
                tr
                  th Pengirim  
                  th Nominal 
                  th Pembayaran Ke Akun Bank
                  th Metode Pembayaran
                  th Pembeli
                tbody.tbody-detail
                  tr
                    td
                      = "#{@confirmation.try(:from_bank_name)} - #{@confirmation.try(:sender_name)} - #{@confirmation.try(:from_account_number)}"
                    td     
                      = get_currency(@confirmation.nominal) if @confirmation.nominal.present?
                    td     
                      = @confirmation.try(:bank_account)
                    td     
                      = @confirmation.try(:payment_method)
                    td
                      = @confirmation.try(:name)
          .message-detail-order
            b Pesan :
            | &nbsp;
            = @confirmation.message
            br
            = image_tag @confirmation.file, style: 'height: 300px' if @confirmation.file.present?
        .footer-detail-order
          b.fa.fa-check
          br
          | Konfirmasi Cocok Dengan Invoice
    - else
      .row
        .panel-body.mg-top15
          .title-show-confirmation
            | Belum Konfirmasi Pembayaran
  .panel-body.mg-top15
    .title-show-confirmation
      | INVOICE <b>#{@order.code.upcase}</b>
      .desc.mg-top10
        b Tanggal Transaksi : 
        = @order.try(:purchased_at).strftime("%B, %d, %Y") if @order.purchased_at
      .desc.mg-bot10
        b Masa Terakhir Dibayar : 
        = (@order.try(:purchased_at)+ 3.days).strftime("%B, %d, %Y") if @order.purchased_at
    .table-responsive.table-detail-invoice
      table.table.table-striped.table-1000.table-bordered.table-hover
        thead.thead-detail
          tr
            th 
              | Dari Toko &nbsp;
              - link_reseller = current_user.account_manager? ? managers_member_path(@order.member) : "#"
              = link_to @order.member.shop_title?, link_reseller
              - if current_user.account_manager?
                span , #{@order.member.profile.phone}
            th Satuan 
            th Jumlah 
            th Berat  
            th.tright Harga  
          tbody.tbody-detail
            - @order.order_items.each do |order_item| 
              tr
                td
                  = image_tag order_item.product.cover
                  .title-content-item
                    .info-catalog
                      table
                        tr
                          th
                            | Nama Produk
                          th
                            | :
                          th
                            = link_to "#{order_item.product.title}", product_path(order_item.product.slug+'-'+order_item.catalog.id.to_s), target: "_blank"
                        tr
                          th
                            | Kode Produk
                          th
                            | :
                          th
                            small.uppercase
                              b
                                = order_item.product.code
                        tr
                          th
                            | Varian
                          th
                            | :
                          th
                            = order_item.variant
                        tr
                          th
                            | Pesan
                          th
                            | :
                          th
                            small
                              = order_item.message
                      br
                      = "#{order_item.status? if order_item.cancelled? || order_item.refund?} &nbsp; #{order_item.cancelled_reason?}".html_safe
                td      
                  = get_currency(order_item.price)
                td      
                  = order_item.quantity
                td      
                  | #{order_item.weight} gr
                td.tright      
                  = get_currency(order_item.total_price)
            tr
              td
              td
              td      
              td      
                | #{@order.weight?} gr
              td.tright      
                | #{get_currency(@order.price)}

            - unless @order.cod?
              tr
                td
                td
                td      
                td.td-style     
                  b Pengiriman #{@order.shipping_method.upcase}
                  br
                  small #{@order.origin_name} - #{@order.try(:address).try(:city).try(:titleize)}, Kecamatan #{@order.try(:address).try(:district).try(:titleize)}
                td.tright.td-style       
                  | #{get_currency(@order.shipping_price) if @order.shipping_price.present?}
            tr
              td
              td 
              td      
              td.td-style       
                b TOTAL
              td.tright.td-style       
                | #{get_currency(@order.total_price)}

    .title-tab-detail
      | Pembayaran Ke Nomor Rekening Dibawah Ini
    .table-responsive
      table.table.table-striped.table-bordered.table-hover.mg-top10
        thead.thead-detail
          tr
            th Transaksi 
            th Pembeli 
            th Pembayaran Ke 
            th Status Pembayaran 
            th Total Pembayaran    
        tbody.tbody-detail
          tr
            td.text
              = @order.try(:purchased_at).strftime("%B, %d, %Y") if @order.purchased_at
            td.text
              = "#{@order.try(:payer_name)} (#{link_to @order.try(:payer_email), "mailto:#{@order.try(:payer_email)}" })".html_safe
            td.text
              = @order.try(:payment_to)
            td.text
              = @order.status?
            td.text
              b
                = get_currency(@order.total_price)

    - if @order.cod?
      .title-tab-detail
        | Pengambilan Barang
      .table-responsive
        table.table.table-striped.table-bordered.table-hover.mg-top10
          thead.thead-detail
            tr
              th COD/Ambil stockis dikantor Merchant 
          tbody.tbody-detail
            tr
              td 
                = "#{@order.courier?} #{@order.address_merchant?}".html_safe
    - else
      .title-tab-detail
        | Pengiriman
      .table-responsive
        table.table.table-striped.table-bordered.table-hover.mg-top10
          thead.thead-detail
            tr
              th Penerima      
              th Metode Pengiriman 
              th Phone 
              th Alamat Pengiriman     
              th Status Pengiriman 
              - if @order.shipped?
                th No Resi    
          tbody.tbody-detail
            tr
              td
                = @order.try(:payer_name)
              td
                = @order.try(:shipping_method).try(:upcase)
              td
                = @order.try(:payer_phone)
              td
                = @order.try(:payer_address)
              td
                = @order.status_order?
              - if @order.shipped? && @order.number_shipping.present?
                td
                  = @order.try(:number_shipping)
                  

app/views/members/orders/_order_menu.html.slim
- if current_user.account_manager?
  - orders_link = managers_orders_path
  - confirmations_link = managers_confirmations_path
- else
  - orders_link = members_orders_path
  - confirmations_link = members_confirmations_path
.top-member-menu
  ul
    li
      = link_to 'Daftar Order', orders_link, class: "#{active_sidebar_active?(:orders, :all)}"
    li
      = link_to 'Konfirmasi Pembayaran', confirmations_link, class: "#{active_sidebar_active?(:confirmations, :all)}"

app/views/members/orders/_partial_js.html.slim
.col-md-12.col-xs-12.col-sm-12
  = render 'members/orders/search_order'
  .row
    = render 'members/home/estimate'
  = render 'estimate', key: :commission_member
  .box-table
    .table-responsive
      table.table.table-striped.table-bordered.table-hover.mg-bot0
        thead
          tr
            th Invoice 
            th Pembeli 
            th Pembayaran  
            th Pengiriman  
            th Transaksi  
            th Konfirmasi  
            th Belanja 
            th Pengiriman 
            th Total 
            th Komisi 
        tbody
          - if @collection.blank?
            tr
              td colspan="10" 
                = render "shareds/empty_blank"
          - else
            - @collection.each_with_index do |resource, index|
              tr
                td.uppercase
                  = link_to "#{resource.code}", members_order_path(resource)
                td
                  = resource.payer_name
                td
                  = resource.status?
                td
                  = resource.status_order?
                td
                  = resource.try(:purchased_at).strftime("%B, %d, %Y") 
                td
                  = resource.confirmation?
                td
                  = get_currency(resource.price)
                td
                  = get_currency(resource.shipping_price)
                td
                  = get_currency(resource.total_price)
                td
                  = get_currency(resource.get_commisions_value(:commission_member))
  .widget-foot
    = paginate @collection, remote: true

app/views/members/orders/_progress.html.slim
.bs-wizard style="border-bottom:0;" 
  div class="col-xs-3 bs-wizard-step #{'complete' if @order.track_order==OrderItem::VERIFICATION || @order.track_order==OrderItem::PACKING || @order.track_order==OrderItem::SHIPPED || @order.track_order=='received'}"
    .text-center.bs-wizard-stepnum <b>Verify</b>
    .progress
      .progress-bar
    a.bs-wizard-dot href="#" 
      i.fa.fa-money
  div class="col-xs-3 bs-wizard-step #{'complete' if @order.track_order==OrderItem::PACKING || @order.track_order==OrderItem::SHIPPED || @order.track_order=='received'}"
    /! complete
    .text-center.bs-wizard-stepnum <b>Pengemasan</b>
    .progress
      .progress-bar
    a.bs-wizard-dot href="#"
      i.fa.fa-archive
  div class="col-xs-3 bs-wizard-step #{'complete' if @order.track_order==OrderItem::SHIPPED || @order.track_order=='received'}"
    /! complete
    .text-center.bs-wizard-stepnum <b>Dikirim</b>
    .progress
      .progress-bar
    a.bs-wizard-dot.icon-1 href="#" 
      i.fa.fa-plane
  div class="col-xs-3 bs-wizard-step #{'complete' if @order.track_order=='received'}"
    /! active
    .text-center.bs-wizard-stepnum <b>Diterima</b>
    .progress
      .progress-bar
    a.bs-wizard-dot href="#" 
      i.fa.fa-check

app/views/members/orders/index.html.slim
#wrapper
  .content.animate-panel
    .hpanel
      .row
        .col-md-4.col-xs-12
          .title-member-content 
            b Daftar Order
        .col-md-8.col-xs-12
          = render 'members/orders/order_menu'
        .js-partial_js
          = render 'partial_js'

app/views/members/orders/index.js.erb
<%= render partial: 'shareds/js/analytic', formats: [:js] %>

$('.js-button-export').html("<%= escape_javascript render partial: 'shareds/button_export' %>");