config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'
  get 'contact', to: 'official#contact', as: 'contact'
  post 'create_contact', to: 'official#create_contact', as: 'create_contact'
  get 'home', to: 'official#home', as: 'home'
  get 'faq', to: 'official#faq', as: 'faq'
  get 'policy', to: 'official#policy', as: 'policy'
  get 'aboutus', to: 'official#aboutus', as: 'aboutus'
  get 'faq2', to: 'official#faq2', as: 'faq2'
  get 'catalog', to: 'official#catalog', as: 'catalog'
  get 'under-maintenance', to: 'publics#under_maintenance', as: 'under_maintenance'
  get '404-not-found', to: 'publics#not_found_page', as: 'not_found_page'
  get "sitemap.xml" => "sitemaps#index", format: "xml", as: 'sitemap'

  resources :blogs
  resources :thank_pages
  resources :pages
  resources :subscribes
  resources :landing_pages
  resources :guest_books
  resources :comments
  resources :products
  resources :helps
  resources :about_us
  resources :contacts
  resources :orders do
    collection do
      get :checkout
    end
    member do
      get :review
    end
  end
  resources :order_items, only: [:create, :update, :destroy]
  resources :confirmation_invoices, only: [:new, :create]
  resources :xhrs do
    collection do
      get :cities
      get :shipment_provinces
      get :shipment_cities
      get :shipment_district
      get :shipping_price
      get :sub_categories
      get :sub_categories_catalog
      get :get_invoice_member
      get :get_payment
      get :get_payment_merchant
      get :get_payment_referral
    end
  end

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :recap_payments
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :account_managers do
      collection do
        post :do_multiple_act
      end
    end
    resources :merchants do
      collection do
        post :do_multiple_act
      end
    end
    resources :categories do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        post :do_multiple_act
      end
    end
    resources :orders do
      collection do
        post :do_multiple_act
      end
      member do
        put :change_number_shipping
      end
    end
    resources :order_distributors do
      collection do
        post :do_multiple_act
      end
    end
    resources :order_items do
      collection do
        post :do_multiple_act
      end
    end
    resources :confirmations do
      collection do
        post :do_multiple_act
      end
    end
    resources :affiliates do
      collection do
        post :do_multiple_act
      end
    end
    resources :shipments do
      collection do
        post :do_multiple_act
        post :import
      end
    end
    resources :regions do
      collection do
        post :do_multiple_act
      end
    end
    resources :comments do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :subscribes do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
    resources :catalogs do
      collection do
        post :do_multiple_act
        get :pending
      end
      member do
        get :restore
      end
    end
    resources :packages do
      collection do
        post :do_multiple_act
      end
    end
    resources :invoices do
      collection do
        post :do_multiple_act
      end
    end
    resources :commissions do
      collection do
        post :do_multiple_act
      end
    end
    resources :commission_referrals do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_snapshots do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_merchants do
      collection do
        post :do_multiple_act
      end
    end
    resources :payment_referrals do
      collection do
        post :do_multiple_act
      end
    end
    resources :domain_settings do
      collection do
        post :do_multiple_act
      end
    end
    resources :guest_books
    resources :web_templates do
      collection do
        post :do_multiple_act
      end
    end
    resources :report_refunds do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_presses do
      collection do
        post :do_multiple_act
      end
    end
    resources :request_landing_presses
    resources :brands
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :spendings do
      collection do
        post :do_multiple_act
      end
    end

  end

  namespace :members do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members, only: [:edit, :update, :show]
    get 'change_theme', to: 'members#change_theme', as: 'change_theme'
    put 'update_change_theme/:id', to: 'members#update_change_theme', as: 'update_change_theme'
    resources :catalogs do
      collection do
        get :inactive
        get :pending
        get :archive
        get :download_catalogs
      end
      member do
        get :restore
        put :change_status
      end
    end
    resources :orders do
      member do
        get :detail
      end
    end
    resources :confirmations
    resources :commissions do
      collection do
        get :referral
      end
    end
    resources :payments
    resources :packages do
      collection do
        get :upgrade
      end
    end
    resources :referrals
    resources :settings
    resources :invoices
    resources :affiliates
    resources :managers
    resources :messages
    resources :guest_books
    resources :blogs
    resources :request_landing_presses
    resources :shops do
      member do
        get :review
      end
      collection do
        get :cart
        get :checkout
      end
    end
    resources :report_refunds
    resources :payment_referrals
  end

  namespace :managers do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :account_managers, only: [:edit, :update, :show]
    resources :catalogs do
      collection do
        get :inactive
        get :pending
        get :archive
        get :download_catalogs
      end
      member do
        get :restore
        put :change_status
      end
    end
    resources :orders do
      member do
        get :detail
      end
    end
    resources :confirmations
    resources :commissions
    resources :payments
    resources :invoices
    resources :members do
      member do
        get :click_message
      end
    end
    resources :messages do
      collection do
        post :blast_message
      end
    end
    resources :report_refunds
  end

  namespace :merchants do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :products
    resources :merchants
    resources :payments
    resources :orders do
      member do
        put :change_number_shipping
      end
    end
    resources :order_items
  end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::ApplicationController
  defaults resource_class: Member, collection_name: 'members', instance_name: 'member'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Members", :collection_path

  include MultipleAction

  def index
    @verifieds = collection.verified.active.size 
    @featureds = collection.verified.active.featured.size
    @not_verifieds = collection.not_verified.size
    @not_actives = collection.not_active.size

    if params[:export] == 'true'
      @collection_all = collection
    end
    
    @collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html
      format.js
      format.xls
    end
  end

  def show
    @domain_settings = resource.domain_settings.page(params[:page_domain_settings]).per(per_page)
    @catalogs = resource.catalogs.latest.search_by(params).page(params[:page_catalogs]).per(per_page)
    @orders = resource.orders.latest.search_by(params).page(params[:page_orders]).per(per_page)
    @confirmations = resource.confirmations.latest.search_by(params).page(params[:page_confirmations]).per(per_page)
    @commissions = resource.commissions.latest.search_by(params).page(params[:page_commissions]).per(per_page)
    @commission_referrals = resource.commission_referrals.latest.search_by(params).page(params[:page_commission_referrals]).per(per_page)
    @payment_snapshots = resource.payment_snapshots.latest.search_by(params).page(params[:page_payment_snapshots]).per(per_page)
    @payment_referrals = resource.payment_referrals.latest.search_by(params).page(params[:page_payment_referrals]).per(per_page)
    @report_refunds = resource.report_refunds.latest.search_by(params).page(params[:page_report_refunds]).per(per_page)
    @invoices = resource.invoices.latest.search_by(params).page(params[:page_invoices]).per(per_page)
    @referrals = resource.referrals.latest.search_by(params).page(params[:page_referrals]).per(per_page)
    @request_landing_presses = resource.request_landing_presses.latest.search_by(params).page(params[:page_request_landing_presses]).per(per_page)
    @activities = resource.activities.latest.search_by(params).page(params[:page_activities]).per(per_page)
    @referral_verified = @referrals.verified
    @referral_not_verified = @referrals.not_verified
    @referral_referral1 = @referrals.referral1(resource.id)
    @referral_referral2 = @referrals.referral2(resource.id)
    @referral_referral3 = @referrals.referral3(resource.id)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    super
    new_account_manager = params[:member][:account_manager_id].to_i
    if resource.catalogs.present?
      resource.catalogs.each do |c|
        if new_account_manager != c.account_manager_id
          c.account_manager_id = new_account_manager
          c.save
        end
      end
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by_member(params)
    end
end

app/controllers/managers/members_controller.rb
class Managers::MembersController < Managers::ApplicationController
  defaults resource_class: Member, collection_name: 'members', instance_name: 'member'

  add_breadcrumb "Dashboard", :managers_dashboard_path
  add_breadcrumb "Resellers", :collection_path

  def index
    @collection_size = collection.size

    if params[:export] == 'true'
      @collection_all = collection.latest
    end
    @collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def show
    add_breadcrumb "messages"
    if resource.account_manager_id == current_user.id
      @profile = resource.profile
      check_group_message_member(@manager.id, resource.id)

      if @latest_messages.where(from: resource.id).present?
        @latest_messages.where(from: resource.id).each do |m|
          m.status = 'read'
          m.save
        end
      end
    else
      redirect_to :back, alert: "You can not access this page because he/she is not your reseller."
    end
  end

  def click_message
    message = Message.find(params[:message_id])
    message.status = "read"
    message.save

    redirect_to managers_member_path(params[:id])
  end
  
  protected
    def collection
       @collection = @manager.members.search_by_member(params)
    end
end

app/controllers/members/affiliates_controller.rb
class Members::AffiliatesController < Members::ApplicationController
	defaults resource_class: Affiliate, collection_name: 'affiliates', instance_name: 'affiliate'

  add_breadcrumb "Dashboard", :members_dashboard_path
  add_breadcrumb "Affiliates", :collection_path

  def index
    @collection_pending = collection.pending.sum(:fee_member)
    @collection_process = collection.process.sum(:fee_member)
    @collection_paid = collection.paid.sum(:fee_member)
    @collection_rejects = collection.rejects.sum(:fee_member)

    @collection_size = collection.size

    if params[:export] == 'true'
      @collection_all = collection.latest
    end
  	@collection = collection.latest.page(page).per(per_page)

    respond_to do |format|
      format.html 
      format.xls
      format.js
      format.xls
    end
  end

  protected
    def collection
       @collection = @member.affiliates.search_by(params)
    end
end

app/controllers/members/application_controller.rb
class Members::ApplicationController < Backend::ResourcesController
	layout 'userpage'

	before_action :authenticate_member!
	before_action :check_profile
	protect_from_forgery with: :exception
  helper_method :current_order

	def authenticate_member!
		unless current_user.present? && (current_user.member?)
			redirect_to root_path, alert: "Can't Access this page"
		else
			@member = Member.find_by(id: current_user.id)
			if @member.present? && @member.invoices.present?
				if current_user.membership == false
					reset_session
					redirect_to new_user_session_path, alert: "Maaf status membership anda untuk sementara di nonaktifkan, silahkan hubungi customer service kami untuk informasi lebih lanjut!"
				end
        @subdomain = @member
        @setting = @subdomain.web_setting
				check_group_message(current_user.id, current_user.account_manager_id)
				@guest_books_latest = GuestBook.where(user_id: current_user.id)
        @last_commissions = @member.commissions.latest.limit(5)
			end
		end
	end

	def check_group_message(member_id, account_manager_id)
		@group_message = GroupMessage.where(member_id: member_id, account_manager_id: account_manager_id).first

		if @group_message.blank?
			@group_message = GroupMessage.create(member_id: member_id, account_manager_id: account_manager_id, status: 'active')
		end

		if @group_message.present?
			@messages = @group_message.messages.oldest
			@latest_messages = @group_message.messages.where(to: member_id).latest
		end
	end

	protected
		def per_page
			params[:per_page] ||= 20
		end

		def page
			params[:page] ||= 1
		end

    def current_order
      if !session[:order_id].nil?
        Order.find(session[:order_id])
      else
        Order.new
      end
    end
end

app/controllers/members/blogs_controller.rb
class Members::BlogsController < Members::ApplicationController
	defaults resource_class: Blog, collection_name: 'blogs', instance_name: 'blog'

  def index
    @blogs_active = collection.active.count
    @collection = collection.latest.active.page(page).per(20)

    respond_to do |format|
    	format.html
    	format.js
    	format.xls
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/members/commissions_controller.rb
class Members::CommissionsController < Members::ApplicationController
  add_breadcrumb "Komisi", :members_commissions_path

  def index
    commission_report_day(@member.commissions, 'with_search_by', :commission_member, 'order', params[:export])

    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end

  def referral
    target_payment_referral(@member)
    commission_report_day(@member.commission_referrals, 'with_search_by', :commission_value, 'referral', params[:export])
    
    respond_to do |format|
      format.html 
      format.xls
      format.js
    end
  end
end

app/controllers/members/confirmations_controller.rb
class Members::ConfirmationsController < Members::ApplicationController
  defaults resource_class: Confirmation, collection_name: 'confirmations', instance_name: 'confirmation'

  add_breadcrumb "Dashboard", :members_dashboard_path
  add_breadcrumb "Pesanan", :members_orders_path
  add_breadcrumb "Konfirmasi Pembayaran", :collection_path

  def index
    @collection = @member.confirmations.search_by(params).latest.page(page).per(per_page)
  end

  def new
    @confirmation = Confirmation.new
  end

  def create
    check_invoice(params[:confirmation][:no_invoice])

    if @invoice.present?
      @confirmation = Confirmation.new(permitted_params)
      @confirmation.member_id = @subdomain.id
      @confirmation.account_manager_id = @confirmation.member.account_manager_id
      @confirmation.order_id = @invoice.id
      if @confirmation.save
        UserMailer.send_confirmation(@confirmation).deliver
        redirect_to members_confirmations_path, notice: 'Anda telah berhasil mengirim Konfirmasi Pembayaran anda, silahkan tunggu kami akan melakukan proses pengecekan terlebih dahulu maximal menunggu 1x24 jam!'
      else
        flash[:errors] = @confirmation.errors.full_messages
        redirect_to request.referer || members_orders_path
      end
    else
      redirect_to request.referer || members_orders_path, alert: 'Tidak ada nomor invoice yang ditemukan!'
    end
  end

  private
    def permitted_params
      params.require(:confirmation).permit(Permitable.controller("confirmation_invoices"))
    end

    def check_invoice(no_invoice)
      @invoice = Order.find_by(code: no_invoice.downcase)
    end

end

app/views/members/members/_form.html.slim
#wrapper
  .content.content-setting.animate-panel
    .hpanel
      .title-member-content
        b Settings
      .title-tab-edit
        i.fa.fa-pencil
        | &nbsp; Edit Setting
      .panel-body
        .tabbable
          ul.nav.nav-tabs
            li.active
              | <a href="#personal" aria-controls="personal" role="tab" data-toggle="tab">Personal data</a></li>
            li role="presentation"
              | <a href="#contact" aria-controls="contact" role="tab" data-toggle="tab">Personal Kontak</a></li>
            li role="presentation"
              | <a href="#address" aria-controls="address" role="tab" data-toggle="tab">Alamat</a></li>
            li role="presentation"
              | <a href="#bank_account" aria-controls="bank_account" role="tab" data-toggle="tab">Rekening Bank</a></li>
            li role="presentation"
              | <a href="#site_info" aria-controls="site_info" role="tab" data-toggle="tab">Pengaturan Domain</a></li>
            li role="presentation"
              | <a href="#web_setting" aria-controls="web_setting" role="tab" data-toggle="tab">Pengaturan Web</a></li>
            li role="presentation"
              | <a href="#setting_seo" aria-controls="setting_seo" role="tab" data-toggle="tab">Setting Toko & SEO</a></li>

          = f.fields_for :profile do |profile|
            = f.fields_for :address do |address|
              = f.fields_for :contact do |contact|
                = f.fields_for :site_info do |site_info|
                  = f.fields_for :web_setting do |web_setting|
                    .tab-content
                      = render partial: 'members/users/form_user', locals: {f: f, profile: profile}
                      = render partial: 'members/users/form_contact', locals: {contact: contact, profile: profile}
                      = render partial: 'members/users/form_address', locals: {address: address}
                      = render partial: 'members/users/form_bank_account', locals: {profile: profile}
                      = render partial: 'members/users/form_site_info', locals: {site_info: site_info, f:f} 
                      = render partial: 'members/users/form_web_setting', locals: {web_setting: web_setting, site_info: site_info} 
                      = render partial: 'members/users/form_setting_seo', locals: {web_setting: web_setting}
      
        .buttons
          button class="btn btn-gb pull-right" type="submit" id="profilebutton" SIMPAN

// javascript:
//   $('#profilebutton').click(function () {
//     $(':required:invalid', "#edit_member_#{current_user.id}").each(function () {
//       var id = $('.tab-pane').find(':required:invalid').closest('.tab-pane').attr('id');

//       $('.nav a[href="#' + id + '"]').tab('show');
//     });
//   });

app/views/members/members/change_theme.html.slim
#wrapper
  .content.content-setting.animate-panel
    .hpanel
      .row
        .col-md-6
          .title-member-content
            b  Pengaturan Tampilan Web
        .col-md-6
          .top-member-menu
            ul
              li
                = link_to '<i class="fa fa-eye"></i> Preview'.html_safe,"http://#{@member.domain? rescue ''}", class: "#{active_sidebar_active?(:request_landing_presses, :index)}", target: '_blank'
      .title-tab-edit
        i.pe-7s-monitor
        | &nbsp; Pilih Tampilan Website
      .panel-body
        .row
          = form_for @member, url: members_update_change_theme_path(@member), method: 'put' do |f|
            = f.fields_for :site_info do |site_info|
              = f.fields_for :web_setting do |web_setting|
                / - if @member.member? && @member.package.premium_or_advance? == true
                - if get_web_templates.present?
                  br
                  - get_web_templates.each do |resource|
                    - if site_info.object.web_template_id == resource.id
                      - selected = 'opacity checked'
                    - else
                      - selected = ''
                    .col-md-3
                      .box-template-web.template-web class="#{selected}"
                        label.lbswatches.line-image.request-template
                          i.fa.fa-check.text-green
                          .scroll style="background-image: url(#{resource.image.url});"
                          h5 #{resource.name}
                          = site_info.radio_button :web_template_id, resource.id
            .col-md-12
              .buttons
                button class="btn btn-gb pull-right" type="submit" id="profilebutton" SIMPAN

app/views/members/members/edit.html.slim
= render partial: 'members/shareds/prepare_form',
            locals: { form_name: 'Members', action_name: 'Edit', form_method: 'put'} 